config/routes.rb
require 'resque/scheduler/server'

Rails.application.routes.draw do

mount Resque::Server.new, :at => '/resque'

  resources :reports do
    member do
      get 'showpdf'
    end
  end

  resources :grants
  devise_for :users
  resources :measurements do
    get 'autocomplete_technique_name', :on => :collection
  end

  resources :techniques
  resources :measurements
  get 'static_pages/home'

  get 'static_pages/help'

  resources :teams
  resources :institutions do
    get 'get_institutions', :on => :collection
  end
  
  resources :clients do
    resources :orders
  end  

  match 'clients/get_team_options/:institution_id', :controller=>'clients', :action => 'get_team_options' , :via  => 'get'
  match 'clients/get_clients_in_team/:team_id', :controller=>'clients', :action => 'get_clients_in_team' , :via  => 'get'
  match 'clients/get_client_grants/:client_id', :controller=>'clients', :action => 'get_client_grants' , :via  => 'get'
  match 'orders/get_grant_options/:client_id', :controller=>'orders', :action => 'get_grant_options' , :via  => 'get'
  match 'teams/get_team_grants/:team_id', :controller=>'teams', :action => 'get_team_grants' , :via  => 'get'
  match 'institutions/get_clients/:institution_id', :controller=>'institutions', :action => 'get_clients' , :via  => 'get'

    get 'orders/gotindex/:status' => 'orders#gotindex'

  root 'static_pages#home'

  resources :orders do
    get 'autocomplete_client_name', :on => :collection
    post 'change_status', :on => :collection
    get 'get_alertcontent', :on => :collection
  end

  resources :orders

end

app/models/institution.rb
class Institution < ActiveRecord::Base
	has_many :clients
	has_many :teams, dependent: :destroy

	accepts_nested_attributes_for :teams, :reject_if => :all_blank, :allow_destroy => true

	validates_presence_of :name, :short_name


def self.search(search)
  if search.present?
    self.where("name LIKE ? or short_name LIKE ?", "%#{search}%", "%#{search}%").all
  else
    self.all
  end
end




end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.search(params[:search]).order(:name).paginate(:page => params[:page], :per_page => 30) 
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
    @teams = @institution.teams.order(:name)
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_clients
    institution = Institution.find(params[:institution_id])
    options = institution.clients.collect{|x| "'#{x.id}':'#{x.full_name}'"}
    render :text => "{#{options.join(",").gsub!("'", '"')}}"
  end

  def get_institutions
    @institutions = Institution.order(:name).select(:id,:name).all   
    render json:  @institutions
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :short_name, :i_type, :address_line1, :address_line2, teams_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= nested_form_for(@institution) do |f| %>
  <% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table table-striped">
<tr>
  <td>

  <div class="panel panel-default">
  <div class="panel-heading">INSTITUTION</div>
  <div class="panel-body">

  <div class="field">
    <%= f.label :name %>*<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :short_name %>*<br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label "Type" %>*<br>
    <%= f.select :i_type, options_for_select([ "NON-COMMERCIAL", "COMMERCIAL", "1 INSTITUTION" ], f.object.i_type ) %>
  </div>
  <div class="field">
    <%= f.label :address_line1 %><br>
    <%= f.text_field :address_line1 %>
  </div>
  <div class="field">
    <%= f.label :address_line2 %><br>
    <%= f.text_field :address_line2 %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
  </div>

  </div>
  </div>

  </td>

  <td style="width:40%">
  <div class="panel panel-default">
  <div class="panel-heading">TEAMS</div>
  <div class="panel-body">
    <%= f.fields_for :teams, @teams do |team| %>
      <div class="field">
        <%= team.label :name %>:
        <%= team.text_field :name, style: "width: 75%" %>
        <%= team.link_to_remove "Remove", role: "button", class: "btn btn-default btn-xs" %>
      </div>
    <% end %>
    <p><%= f.link_to_add "Add a team", :teams, role: "button", class: "btn btn-default" %></p>
  </div>
  </div>
    
  </td>



</tr>
</table>



<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution, class: "btn btn-default" %> |
<%= link_to 'Back', institutions_path, class: "btn btn-default" %>

app/views/institutions/index.html.erb
<table>
<tr>
<td>
<%= form_tag institutions_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], id: 'small', autocomplete: 'off' %>
    <%= submit_tag "Search", id: 'btsmall' %>
  </p>
<% end %>
</td>
<td width="70%">
<h1>Listing Institutions</h1>
</td>
</tr>  
</table>

<%= link_to 'New Institution', new_institution_path, class: "btn btn-default" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name <span class="glyphicon glyphicon-search"></th>
      <th>Short name <span class="glyphicon glyphicon-search"></th>
      <th>Type</th>
      <th>Address line1</th>
      <th>Address line2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.short_name %></td>
        <td><%= institution.i_type %></td>
        <td><%= institution.address_line1 %></td>
        <td><%= institution.address_line2 %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
      <% if current_user.admin? %>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @institutions, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'New Institution', new_institution_path, class: "btn btn-default" %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path, class: "btn btn-default" %>

app/views/institutions/show.html.erb
<table class="table table-striped">

<tr>
<td style="width:60%">

  <div class="panel panel-default">
  <div class="panel-heading">INSTITUTION</div>
  <div class="panel-body">

<ul class="list-group">
	<li class="list-group-item">
	  <strong>Name:</strong>
	  <%= @institution.name %>
  	</li>
	<li class="list-group-item">
	  <strong>Short name:</strong>
	  <%= @institution.short_name %>
  	</li>
  <li class="list-group-item">
    <strong>Type:</strong>
    <%= @institution.i_type %>
    </li>
	<li class="list-group-item">
	  <strong>Address line1:</strong>
	  <%= @institution.address_line1 %>
  	</li>
  	<li class="list-group-item">
	  <strong>Address line2:</strong>
	  <%= @institution.address_line2 %>
  	</li>

</ul>
  </div>
  </div>

</td>
<td style="width:40%">

  <div class="panel panel-default">
  <div class="panel-heading">TEAMS</div>
  <div class="panel-body">
  	<ul class="list-group">
    <% @institution.teams.each do |team| %>
    	<li class="list-group-item">      
        <%= team.name %> <%= link_to 'Show', team, class: "btn btn-default btn-xs" %> <%= link_to 'Edit', edit_team_path(team), class: "btn btn-default btn-xs" %>        
    	</li>
    <% end %>
    </ul>
  </div>
  </div>

</td>
</tr>

</table>

<%= link_to 'Edit', edit_institution_path(@institution), class: "btn btn-default" %> |
<%= link_to 'Back to Institutions', institutions_path, class: "btn btn-default" %>