config/routes.rb
require 'resque/scheduler/server'

Rails.application.routes.draw do

mount Resque::Server.new, :at => '/resque'

  resources :reports do
    member do
      get 'showpdf'
    end
  end

  resources :grants
  devise_for :users
  resources :measurements do
    get 'autocomplete_technique_name', :on => :collection
  end

  resources :techniques
  resources :measurements
  get 'static_pages/home'

  get 'static_pages/help'

  resources :teams
  resources :institutions do
    get 'get_institutions', :on => :collection
  end
  
  resources :clients do
    resources :orders
  end  

  match 'clients/get_team_options/:institution_id', :controller=>'clients', :action => 'get_team_options' , :via  => 'get'
  match 'clients/get_clients_in_team/:team_id', :controller=>'clients', :action => 'get_clients_in_team' , :via  => 'get'
  match 'clients/get_client_grants/:client_id', :controller=>'clients', :action => 'get_client_grants' , :via  => 'get'
  match 'orders/get_grant_options/:client_id', :controller=>'orders', :action => 'get_grant_options' , :via  => 'get'
  match 'teams/get_team_grants/:team_id', :controller=>'teams', :action => 'get_team_grants' , :via  => 'get'
  match 'institutions/get_clients/:institution_id', :controller=>'institutions', :action => 'get_clients' , :via  => 'get'

    get 'orders/gotindex/:status' => 'orders#gotindex'

  root 'static_pages#home'

  resources :orders do
    get 'autocomplete_client_name', :on => :collection
    post 'change_status', :on => :collection
    get 'get_alertcontent', :on => :collection
  end

  resources :orders

end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :institution
	belongs_to :team
	has_many :orders
	has_and_belongs_to_many :grants
	
	accepts_nested_attributes_for :grants, :reject_if => :all_blank, :allow_destroy => true

	after_save :load_into_soulmate
	before_destroy :remove_from_soulmate

	validates_presence_of :first_name, :last_name, :institution_id, :team_id

  def full_name
  	[last_name, first_name].join(' ')
  end


  def self.search(term)
    matches = Soulmate::Matcher.new('clients').matches_for_term(term)
    matches.collect {|match| {"id" => match["id"], "value" => match["term"] } }
  end


def self.szukaj(search)
  if search.present?
    self.where("last_name LIKE ? or first_name LIKE ?", "%#{search}%", "%#{search}%" ).all
  else
    self.all
  end
end



private 

	def load_into_soulmate
		imie = last_name + " " + first_name
		loader = Soulmate::Loader.new("clients")
		loader.add("term" => imie, "id" => self.id)
	end

	def remove_from_soulmate
		loader = Soulmate::Loader.new("clients")
	    loader.remove("id" => self.id)
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.szukaj(params[:search]).order(:last_name).paginate(:page => params[:page], :per_page => 30)    
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @institutions = Institution.all.order(:name)
    @teams = Team.all   
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
    @institutions = Institution.all 
    @teams = @client.institution.teams 
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    
    respond_to do |format|
      if @client.save
        format.html { redirect_to edit_client_path(@client), notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @client.attributes = {'grant_ids' => []}.merge(params[:client] || {})
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_team_options
    inst = Institution.find(params[:institution_id])
    options = inst.teams.collect{|x| "'#{x.id}':'#{x.name}'"}
    render :text => "{#{options.join(",").gsub!("'", '"')}}"
  end

  def get_clients_in_team
    team = Team.find(params[:team_id])
    options = team.clients.collect{|x| "'#{x.id}':'#{x.last_name} #{x.first_name}'"}
    render :text => "{#{options.join(",").gsub!("'", '"')}}"    
  end

  def get_client_grants
    client = Client.find(params[:client_id])
    options = client.grants.collect{|x| "'#{x.id}':'#{x.name}'"}
    render :text => "{#{options.join(",").gsub!("'", '"')}}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :institution_id, :email, :phone, :team_id, { grant_ids: [] })     
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table table-striped">
<tr>
  <td>

  <div class="panel panel-default">
  <div class="panel-heading">CLIENT</div>
  <div class="panel-body">

  <div class="field">
    <%= f.label :first_name %>*<br>
    <%= f.text_field :first_name, autocomplete: 'off' %>
  </div>
  <div class="field">
    <%= f.label :last_name %>*<br>
    <%= f.text_field :last_name, autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= f.label "Institution" %>*<br>
    <%= f.select :institution_id, options_from_collection_for_select(@institutions, :id, :name, @client.institution_id ), {prompt: '---  Select Institution  ---'},  id: "client_institution_id_ps" %>
  </div>

  <div class="field">
    <%= f.label "Team" %>*<br>
    <%= f.select :team_id, options_from_collection_for_select(@teams, :id, :name, @client.team_id ), {prompt: '---  Select Team in the Institution  ---'}, id: "client_team_id_ps" %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, autocomplete: 'off' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
  </div>

  </div>
  </div>

  </td>

  <td style="width:40%">
  <% if current_page?(controller: 'clients', action: 'new') %>
  <% else %>
  <div class="panel panel-default">
  <div class="panel-heading">GRANTS</div>
  <div class="panel-body">
  <table class="table table-striped">
    <% if @client.team.grants.empty? %>
      <p>Nie przypisano jeszcze żadnego grantu dla tego zespołu</p><br>
      Aby dodać grant: 
      <%= link_to 'Idź do edycji zespołu', edit_team_path(@client.team), class: "btn btn-default" %>
    <% else %>
      <% @client.team.grants.where(active: true).each do |grant| %>
      <tr>
      <td><%= check_box_tag "client[grant_ids][]", grant.id, f.object.grants.include?(grant), style: "height: auto !important; width:30px" %></td>
      <td><%= grant.name %>  - <font color="green"><b><%= grant.active ? "Aktywny" : "Nieaktywny"  %></b></font> - <%= link_to 'Edit', edit_grant_path(grant), class: "btn btn-default btn-xs" %></td>
      </tr>
      <% end %>
    <% end %>

  </table>
 nie zapomnij kliknąć Update Client po dokonaniu zmian 
  </div>
  </div>
  <% end %>



  <% if current_page?(controller: 'clients', action: 'new') %>
  <% else %>
  <div class="panel panel-default">
  <div class="panel-heading">INACTIVE GRANTS</div>
  <div class="panel-body">
  <table class="table table-striped">
    <% if @client.team.grants.where(active: false).empty? %>
      <p>Nie ma nieaktywnych grantów dla tego klienta</p><br>
    <% else %>
      <% @client.team.grants.where(active: false).each do |grant| %>
      <tr>
      <td><%= check_box_tag "client[grant_ids][]", grant.id, f.object.grants.include?(grant), style: "height: auto !important; width:30px" %></td>
      <td><%= grant.name %>  - <font color="green"><b><%= grant.active ? "Aktywny" : "Nieaktywny"  %></b></font> - <%= link_to 'Edit', edit_grant_path(grant), class: "btn btn-default btn-xs" %></td>
      </tr>
      <% end %>
    <% end %>

  </table>
  </div>
  </div>
  <% end %>






  </td>
  </tr>
</table>


<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client, class: "btn btn-default" %> |
<%= link_to 'Back', clients_path, class: "btn btn-default" %>

app/views/clients/index.html.erb
<table>
<tr>
<td>
<%= form_tag clients_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], id: 'small', autocomplete: 'off' %>
    <%= submit_tag "Search", :last_name => nil, id: 'btsmall' %>
  </p>
<% end %>
</td>
<td width="70%">
<h1>Listing Clients</h1>
</td>
</tr>  
</table>


<%= link_to 'New Client', new_client_path, class: "btn btn-default" %>




<table class="table table-striped">
  <thead>
    <tr>
      <th>Last name <span class="glyphicon glyphicon-search"></th>
      <th>First name <span class="glyphicon glyphicon-search"></th>
      <th>Institution</th>
      <th>Team</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.last_name %></td>
        <td><%= client.first_name %></td>        
        <td><%= client.institution.name %></td>
        <td><%= client.team.name %></td>
        <td><%= client.email %></td>
        <td><%= client.phone %></td>
        <td><%= link_to 'Orders', client_orders_path(client) %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
      <% if current_user.admin? %>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @clients, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'New Client', new_client_path, class: "btn btn-default" %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path, class: "btn btn-default" %>

app/views/clients/show.html.erb
<table class="table table-striped">

<tr>
<td style="width:60%">

  <div class="panel panel-default">
  <div class="panel-heading">INSTITUTION</div>
  <div class="panel-body">

<ul class="list-group">
	<li class="list-group-item">
  <strong>First name:</strong>
  <%= @client.first_name %>
  	</li>
	<li class="list-group-item">
  <strong>Last name:</strong>
  <%= @client.last_name %>
  	</li>
	<li class="list-group-item">
  <strong>Institution:</strong>
  <%= @client.institution.name %>
  	</li>
  	<li class="list-group-item">
  <strong>Team:</strong>
  <%= @client.team.name %>
  	</li>
    <li class="list-group-item">
  <strong>Email:</strong>
  <%= @client.email %>
    </li>
    <li class="list-group-item">
  <strong>Phone number:</strong>
  <%= @client.phone %>
    </li>


</ul>
  </div>
  </div>
</td>

<td style="width:40%">

  <div class="panel panel-default">
  <div class="panel-heading">GRANTS</div>
  <div class="panel-body">
  	<ul class="list-group">

      <% @client.grants.each do |grant| %>
      <li class="list-group-item"> 
        <%= grant.name %></br>
      </li>
      <% end %>

    </ul>
  </div>
  </div>

</td>
</tr>

</table>



<%= link_to 'Edit', edit_client_path(@client), class: "btn btn-default" %> |
<%= link_to 'Go to Clients', clients_path, class: "btn btn-default" %> |
<%= link_to 'Client Orders', client_orders_path(@client), class: "btn btn-default" %>