config/routes.rb
require 'resque/scheduler/server'

Rails.application.routes.draw do

mount Resque::Server.new, :at => '/resque'

  resources :reports do
    member do
      get 'showpdf'
    end
  end

  resources :grants
  devise_for :users
  resources :measurements do
    get 'autocomplete_technique_name', :on => :collection
  end

  resources :techniques
  resources :measurements
  get 'static_pages/home'

  get 'static_pages/help'

  resources :teams
  resources :institutions do
    get 'get_institutions', :on => :collection
  end
  
  resources :clients do
    resources :orders
  end  

  match 'clients/get_team_options/:institution_id', :controller=>'clients', :action => 'get_team_options' , :via  => 'get'
  match 'clients/get_clients_in_team/:team_id', :controller=>'clients', :action => 'get_clients_in_team' , :via  => 'get'
  match 'clients/get_client_grants/:client_id', :controller=>'clients', :action => 'get_client_grants' , :via  => 'get'
  match 'orders/get_grant_options/:client_id', :controller=>'orders', :action => 'get_grant_options' , :via  => 'get'
  match 'teams/get_team_grants/:team_id', :controller=>'teams', :action => 'get_team_grants' , :via  => 'get'
  match 'institutions/get_clients/:institution_id', :controller=>'institutions', :action => 'get_clients' , :via  => 'get'

    get 'orders/gotindex/:status' => 'orders#gotindex'

  root 'static_pages#home'

  resources :orders do
    get 'autocomplete_client_name', :on => :collection
    post 'change_status', :on => :collection
    get 'get_alertcontent', :on => :collection
  end

  resources :orders

end

app/models/grant.rb
class Grant < ActiveRecord::Base
	has_and_belongs_to_many :clients
	belongs_to :team
	has_many :orders
	

	validates_presence_of :name, :short_name


def self.search(search)
  if search.present?
    self.where("name LIKE ? or short_name LIKE ?", "%#{search}%", "%#{search}%").all
  else
    self.all
  end
end



end

app/models/institution.rb
class Institution < ActiveRecord::Base
	has_many :clients
	has_many :teams, dependent: :destroy

	accepts_nested_attributes_for :teams, :reject_if => :all_blank, :allow_destroy => true

	validates_presence_of :name, :short_name


def self.search(search)
  if search.present?
    self.where("name LIKE ? or short_name LIKE ?", "%#{search}%", "%#{search}%").all
  else
    self.all
  end
end




end

app/models/report.rb
class Report < ActiveRecord::Base

#validates_presence_of :name, :date_from, :date_to, :i_type
#validates_presence_of :institution, :team, :grant, if: :is_ichogrant?
#validates_presence_of :institution, if: :i_type == "1 INSTITUTION"


#def is_ichogrant?
#  i_type == "1 GRANT"
#end

end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :institution
  has_many :clients
  has_many :grants

  accepts_nested_attributes_for :grants, :reject_if => :all_blank, :allow_destroy => true

  validates_presence_of :name
  validates_uniqueness_of :name

  def full_name
  	[name, self.institution.short_name].join(' - ')
  end


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :showpdf, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all.paginate(:page => params[:page], :per_page => 30) 
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  # dla icho 1 grant
    @orders = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to, grant_id: @report.grant)  
    @order_ids = @orders.collect(&:id)
    @clients = Client.where(id: @orders.collect(&:client_id))
  # wszyscy
    @grant_ids = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to).collect(&:grant_id)
    @team_ids = Grant.where(id: @grant_ids).collect(&:team_id)
  # dla komercyjnych i niekomercyjnych
  case @report.i_type 
  when "NON-COMMERCIAL"    
    @niekomercyjni = Institution.where(i_type: "NON-COMMERCIAL")
  when "COMMERCIAL"
    @niekomercyjni = Institution.where(i_type: "COMMERCIAL")
  end
  # dla icho
    @institution = Institution.find(@report.institution) unless @report.institution.blank?
    @teams = @institution.teams.where(id: @team_ids).order(:name) unless @report.team.blank? && @report.institution.blank?
    @techniques = Technique.all    
  end

  def showpdf
  # dla icho 1 grant
    @orders = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to, grant_id: @report.grant)  
    @order_ids = @orders.collect(&:id)
    @clients = Client.where(id: @orders.collect(&:client_id))
  # wszyscy
    @grant_ids = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to).collect(&:grant_id)
    @team_ids = Grant.where(id: @grant_ids).collect(&:team_id)
  # dla komercyjnych niekomercyjnych    
  case @report.i_type 
  when "NON-COMMERCIAL"    
    @niekomercyjni = Institution.where(i_type: "NON-COMMERCIAL")
  when "COMMERCIAL"
    @niekomercyjni = Institution.where(i_type: "COMMERCIAL")
  end   
  # dla icho
    @institution = Institution.find(@report.institution) unless @report.institution.blank?
    @teams = @institution.teams.where(id: @team_ids).order(:name) unless @report.team.blank? && @report.institution.blank?
    @techniques = Technique.all 

      #if File.exist?(Rails.root.join('app','assets','pdfs', "#{@report.id}.pdf"))
      #  send_file(Rails.root.join('app','assets','pdfs', "#{@report.id}.pdf"), :filename => "#{@report.id}.pdf", :disposition => 'inline', :type => "application/pdf")
      #else
        render :pdf    => "#{@report.id}.pdf",
          :disposition => "inline",
          :template    => "reports/showpdf.html.erb", 
          :encoding    => "UTF-8",
          :orientation => 'Landscape',
          page_size: 'A4',
          footer: { right: '[page] of [topage]' }
          #save_to_file: Rails.root.join('app','assets','pdfs', "#{@report.id}.pdf")
      #end

  end

  # GET /reports/new
  def new
    @report = Report.new
    @institutions = Institution.all
    @teams = Team.all
    @clients = Client.all
    @grants = Grant.all
  end

  # GET /reports/1/edit
  def edit
    @institutions = Institution.all
    @report.team.nil? ? @teams = Team.all : @teams = Institution.find(@report.institution.to_i).teams
    @report.team.nil? ? @clients = Client.all : @clients = Team.find(@report.team.to_i).clients
    @report.team.nil? ? @grants = Grant.all : @grants = Team.find(@report.team.to_i).grants
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

     # dla icho 1 grant
    @orders = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to, grant_id: @report.grant)  
    @order_ids = @orders.collect(&:id)
    @clients = Client.where(id: @orders.collect(&:client_id))
  # wszyscy
    @grant_ids = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to).collect(&:grant_id)
    @team_ids = Grant.where(id: @grant_ids).collect(&:team_id)
  # dla komercyjnych i niekomercyjnych
  case @report.i_type 
  when "NON-COMMERCIAL"    
    @niekomercyjni = Institution.where(i_type: "NON-COMMERCIAL")
  when "COMMERCIAL"
    @niekomercyjni = Institution.where(i_type: "COMMERCIAL")
  end
  # dla icho
    @institution = Institution.find(@report.institution) unless @report.institution.blank?
    @teams = @institution.teams.where(id: @team_ids).order(:name) unless @report.team.blank? && @report.institution.blank?
    @techniques = Technique.all

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }

        #pdf = render_to_string :pdf => "#{@report.id}.pdf",
        #  :disposition => "inline",
        #  :template    => "reports/showpdf.html.erb", 
        #  :encoding    => "UTF-8",
        #  page_size: 'A3',
        #  footer: { right: '[page] of [topage]' }

        #save_path = Rails.root.join('app','assets','pdfs',"#{@report.id}.pdf")
        #File.open(save_path, 'wb') do |file|
        #file << pdf
        #end

      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
  # dla icho 1 grant
    @orders = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to, grant_id: @report.grant)  
    @order_ids = @orders.collect(&:id)
    @clients = Client.where(id: @orders.collect(&:client_id))
  # wszyscy
    @grant_ids = Order.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to).collect(&:grant_id)
    @team_ids = Grant.where(id: @grant_ids).collect(&:team_id)
  # dla komercyjnych i niekomercyjnych
  case @report.i_type 
  when "NON-COMMERCIAL"    
    @niekomercyjni = Institution.where(i_type: "NON-COMMERCIAL")
  when "COMMERCIAL"
    @niekomercyjni = Institution.where(i_type: "COMMERCIAL")
  end
  # dla icho
    @institution = Institution.find(@report.institution) unless @report.institution.blank?
    @teams = @institution.teams.where(id: @team_ids).order(:name) unless @report.team.blank? && @report.institution.blank?
    @techniques = Technique.all

    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }

        #pdf = render_to_string :pdf => "#{@report.id}.pdf",
        #  :disposition => "inline",
        #  :template    => "reports/showpdf.html.erb", 
        #  :encoding    => "UTF-8",
        #  page_size: 'A3',
        #  footer: { right: '[page] of [topage]' }
        

        #save_path = Rails.root.join('app','assets','pdfs',"#{@report.id}.pdf")
        #File.open(save_path, 'wb') do |file|
        #file << pdf
        #end


      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      #File.delete(Rails.root.join('app','assets','pdfs',"#{@report.id}.pdf")) if File.exist?(Rails.root.join('app','assets','pdfs',"#{@report.id}.pdf"))
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :date_from, :date_to, :institution, :team, :client, :grant, :i_type)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>*<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date_from %>*<br>
    <%= f.text_field :date_from %>
  </div>
  <div class="field">
    <%= f.label :date_to %>*<br>
    <%= f.text_field :date_to %>
  </div>

  <div class="field">
    <%= f.label "Type of Report" %>*<br>
    <%= f.select :i_type, options_for_select([ "NON-COMMERCIAL", "COMMERCIAL", "1 INSTITUTION", "1 GRANT" ], f.object.i_type ), {prompt: '---  Select Type of Report  ---'},  id: "i_type" %>    
  </div>

  <div class="field">
    <%= f.label :institution %>*<br>
    <%= f.select :institution, options_from_collection_for_select(@institutions, :id, :name, f.object.institution), {prompt: '---  Select Institution  ---'},  id: "client_institution_id_ps" %>    
  </div>
  <div class="field">
    <%= f.label :team %>*<br>
    <%= f.select :team, options_from_collection_for_select(@teams, :id, :name, f.object.team), {prompt: '---  Select Team of Institution  ---'}, id: "client_team_id_ps" %>
  </div>
  <div class="field">
    <%= f.label :grant %>*<br>
    <%= f.select :grant, options_from_collection_for_select(@grants, :id, :name, f.object.grant), {prompt: '---  Select Grant  ---'}, id: "grant_id" %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/reports/_icho.html.erb
<table class="table table-condensed table-bordered">
	<tr>
    	<td colspan="2">
      	<h5><b><%= @institution.name %></b></br></h5>
    	</td>
    	
  	</tr>
  	<tr>
  		<th>Nazwa zespołu</th>
  		<th>Wykonane Pomiary</th>
  	</tr>

										<% @teams.each do |team| %>  	

  	<tr>
  		<td><h5><b><%= team.name %></h5></b></td>

  		<td>
<% team.grants.where(id: @grant_ids).each do |grant| %>
	<% grant_orders = grant.orders.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to).collect(&:id) %>
	<% grant_measurements = Measurement.where(order_id: grant_orders) %>

  			<table class="table table-condensed table-bordered">
  			<caption><%= grant.name %></caption>
				<tr>
					<% @techniques.each do |tech| %>
					<th><%= tech.short_name %></th>
					<% end %>
				</tr>
				<tr>					
					<% @techniques.each do |t| %>
          <% wart = grant_measurements.where(technique_id: t.id).count %>
            <% if wart != 0 %>
					      <td><%= wart %></td>
            <% else %>
                <td>-</td>
					  <% end %>
          <% end %>
				</tr>
  			</table>
<% end %>
  		</td>  							
  	</tr>
										<% end %>										  	
</table>

app/views/reports/_ichogrant.html.erb
<table class="table table-condensed table-bordered">
	<tr>
    	<td colspan="2">
      	<h5><b><%= @institution.name %></b></br></h5>
      	<h5>grant: <i><%= Grant.find(@report.grant).name %></i></br></h5>
    	</td>
    	
  	</tr>
  	<tr>
  		<th>Imię i nazwisko</th>
  		<th>Wykonane Pomiary</th>
  	</tr>

										<% @clients.each do |client| %>  	

  	<tr>
  		<td><h5><b><%= client.full_name %></h5></b></td>

  		<td>


  			<table class="table table-condensed table-bordered">
				<tr>
					<th id="raport">Próbka</th>
					<% @techniques.each do |tech| %>
					<th id="raport"><%= tech.short_name %></th>
					<% end %>
					<th id="raport">Wartość</th>
				</tr>

<% client.orders.where(id: @order_ids).each do |order| %>

	<% order_measurements = order.measurements %>


				<tr>
				<td><%= order.sample_name %></td>					
		<% @techniques.each do |t| %>
          				<% wart = order_measurements.where(technique_id: t.id).count %>
            		<% if wart != 0 %>
					    <td><%= wart %></td>
            		<% else %>
                		<td>-</td>
					<% end %>	
					
        <% end %>
        		<td><%= number_to_currency( order.final_price, unit: "zł", format: "%n %u" )  %></td>
				</tr>

<% end %>


  			</table>

  		</td>  							
  	</tr>
										<% end %>
	

	<tr>
		<td><b>Podsumowanie:</b></td>
		<td>Sumaryczna wartość wykonanych pomiarów: <b><%= number_to_currency( @orders.sum(:final_price), unit: "zł", format: "%n %u" )  %></b></td>
	</tr>										  	
</table>

app/views/reports/_niekomercyjne.html.erb
<table class="table table-condensed table-bordered">
<% @niekomercyjni.each do |n| %>


									<% n.teams.where(id: @team_ids).each do |team| %> 
	<tr>
	   	<td>
      	<b><font size="3"><%= team.institution.name %></font></b></br>
      	<font size="3"><%= team.name %></font></br>
		</td>

  		<td>
	<% team.grants.where(id: @grant_ids).each do |grant| %>
	<% grant_orders = grant.orders.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to) %>
	<% grant_measurements = Measurement.where(order_id: grant_orders.collect(&:id)) %>

  			<table class="table table-condensed table-bordered">
  			<caption><font size="3">Zlecenie/Zamówienie/Grant: <u><%= grant.name %></u> </br> Data wykonania: <%= grant_orders.collect(&:order_end_date).max %></font></caption>
				<tr>
					<% @techniques.each do |tech| %>
					<th><%= tech.short_name %></th>
					<% end %>
				</tr>
				<tr>					
					<% @techniques.each do |t| %>

          				<% wart = grant_measurements.where(technique_id: t.id).count %>
            			<% if wart != 0 %>
					      	<td><%= wart %></td>
           				<% else %>
                			<td>-</td>
					    <% end %>

					<% end %>
				</tr>
  			</table>

<% end %>
  		</td>  							
  	</tr>
										<% end %>





<% end %>
</table>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report, class: "btn btn-default" %> |
<%= link_to 'Back', reports_path, class: "btn btn-default" %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date from</th>
      <th>Date to</th>
      <th>Type</th>
      <th>Institution</th>
      <th>Team</th>

      <th>Grant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= report.date_from %></td>
        <td><%= report.date_to %></td>
        <td><%= report.i_type %></td>
        <td><%= Institution.find(report.institution).name unless report.institution.blank? %></td>
        <td><%= Team.find(report.team).name unless report.team.blank? %></td>

        <td><%= Grant.find(report.grant).name unless report.grant.blank? %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Show pdf', showpdf_report_path(report, :format => :pdf) %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
      <% if current_user.admin? %>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @reports, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'New Report', new_report_path, class: "btn btn-default" %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path, class: "btn btn-default" %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-condensed">
	<tr class="success">
		<td><h4>Raport: <%= @report.name %></h4></td>
		<td><h5><strong>Data wykonania od: </strong><%= @report.date_from %> <strong>do: </strong><%= @report.date_to %></h5></td>
	</tr>
	<tr class="active">
    	<td colspan="2">
    	<% case @report.i_type
    		when "NON-COMMERCIAL" %>
      		<%= render 'niekomercyjne' %>
    	<% when "1 INSTITUTION" %>
      		<%= render 'icho' %>
      <% when "COMMERCIAL" %>
          <%= render 'niekomercyjne' %>
      <% when "1 GRANT" %>
          <%= render 'ichogrant' %>                          	
      	<% end %>
    	</td>
  	</tr>
</table>

<%= link_to 'Edit', edit_report_path(@report), class: "btn btn-default" %> |
<%= link_to 'Back to Reports', reports_path, class: "btn btn-default" %>

app/views/reports/show_old.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-condensed">
  <tr class="active">
  <td colspan="3">
    <h4>Report: <%= @report.name %></h4>
  </td>  
  </tr>

  <tr>
  <td colspan="3">
    <strong>Date from: </strong><%= @report.date_from %> 
    <strong>to: </strong>
    <%= @report.date_to %>
  </td>
  </tr>



  <tr class="success">
    <td colspan="3">
      <h5><%= @institution.name %></br></h5>
    </td>
  </tr>

  <% if @report.team.blank? %>

    <% @institution.teams.each do |team| %>
  <tr class="info">
    <td colspan="3">    
      <%= team.name %>
    </td>
  </tr>
      <% team.clients.each do |client| %>

  <tr>
        <% client_orders = client.orders.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to) %>

    <% if client_orders.any? %>
    <td>
      <%= client.full_name %>
    </td>      
    <td>
    <% client.grants.where(id: client_orders.collect(&:grant_id)).each do |grant| %>      




      <table class="table table-bordered">
      <caption><%= grant.short_name %></caption>

      <tr>
        <th>Info</th>

      </tr>
              <% col = 0  %> 
              <% mcol = client.orders.map{|n| n.measurements.count}.max  %>    
    <% client_orders.where(grant_id: grant.id).each do |order| %>
      <tr>
              <% col = order.measurements.count if col < order.measurements.count  %>               
        <td>
          Numer zlecenia: <%= order.number %> | Nazwa próbki: <%= order.sample_name %>
        </td>

       
          <% order.measurements.each do |meas| %>
            <td>
              <%= meas.technique.short_name %>: <%= meas.multiplier %>
            </td>
          <% end %>

          <% if col < mcol  %>
          <% (mcol-col).times do %>
          <td></td>
          <% end %>
          <% end %>
        
        <td>
          Koszt: <%= order.final_price %> zł
        </td>

      </tr>
      <% end %>

      <tr>
        <td colspan="<%= col + 1 %>"><b>Koszt sumaryczny:</b></td>
        <td><%= client_orders.where(grant_id: grant.id).sum(:final_price) %> zł</td>
      </tr>


      </table>

      <% end %>
    </td>

  <% end %>   
  </tr>



      <% end %>
    <% end %>
  <% else %>

  

  <tr class="info">
    <td colspan="3">
      <% zesp = Team.find(@report.team) %>  
      <%= zesp.name %>
    </td>
  </tr>

            <% if @report.client.blank? %>

                      <% zesp.clients.each do |client| %>
<% client_orders = client.orders.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to) %>

  <tr>
    <% if client_orders.any? %>
    <td>
      <%= client.full_name %>
    </td>      
    <td>
    <% client.grants.where(id: client_orders.collect(&:grant_id)).each do |grant| %>      

      <table class="table table-bordered">
      <caption><%= grant.short_name %></caption>

      







      <tr>
        <th>Info</th>

      </tr>
              <% col = 0  %> 
              <% mcol = client_orders.map{|n| n.measurements.count}.max  %>       
    <% client_orders.where(grant_id: grant.id).each do |order| %>
      <tr>
        
        <td>
          Numer zlecenia: <%= order.number %> | Nazwa próbki: <%= order.sample_name %>
        </td>

              <% col = order.measurements.count if col < order.measurements.count  %>        
          <% order.measurements.each do |meas| %>
            <td>
              <%= meas.technique.short_name %>: <%= meas.multiplier %>
            </td>
          <% end %> 
        
          <% if col < mcol  %>
          <% (mcol-col).times do %>
          <td></td>
          <% end %>
          <% end %>

        <td>
          Koszt: <%= order.final_price %> zł
        </td>

      </tr>


      <% end %>

      <tr>
        <td colspan="<%= col + 1 %>"><b>Koszt sumaryczny:</b></td>
        <td><%= client_orders.where(grant_id: grant.id).sum(:final_price) %> zł</td>
      </tr>

      </table>

      <% end %>
    </td>

  <% end %>   
  </tr>
                      <% end %>

              <% else %>








      <% client = Client.find(@report.client) %>
<% client_orders = client.orders.where(status: "ENDED", order_end_date: @report.date_from..@report.date_to) %>
  <tr>
    <% if client_orders.any? %>
    <td>
      <%= client.full_name %>
    </td>




                        <% if @report.grant.blank? %>
    <td>
    <% client.grants.where(id: client_orders.collect(&:grant_id)).each do |grant| %>      

      <table class="table table-bordered">
      <caption><%= grant.short_name %></caption>


      <tr>
        <th>Info</th>

      </tr>
              <% col = 0  %>
              <% mcol = client_orders.map{|n| n.measurements.count}.max  %>      
    <% client_orders.where(grant_id: grant.id).each do |order| %>
      <tr>
        
        <td>
          Numer zlecenia: <%= order.number %> | Nazwa próbki: <%= order.sample_name %>
        </td>

              <% col = order.measurements.count if col < order.measurements.count  %>        
          <% order.measurements.each do |meas| %>
            <td>
              <%= meas.technique.short_name %>: <%= meas.multiplier %>
            </td>
          <% end %> 
        
          <% if col < mcol  %>
          <% (mcol-col).times do %>
          <td></td>
          <% end %>
          <% end %>

        <td>
          Koszt: <%= order.final_price %> zł
        </td>

      </tr>
      <% end %>

      <tr>
        <td colspan="<%= col + 1 %>"><b>Koszt sumaryczny:</b></td>
        <td><%= client_orders.where(grant_id: grant.id).sum(:final_price) %> zł</td>
      </tr>


     
      </table>

      <% end %>
    </td>





                        <% else %>

    <td>
    <% grant = Grant.find(@report.grant) %>      

      <table class="table table-bordered">
      <caption><%= grant.short_name %></caption>

      <tr>
        <th>Info</th>
<% col = 0  %>
<% mcol = client.orders.map{|n| n.measurements.count}.max  %>  
      </tr>
    <% client.orders.where(grant_id: grant.id, status: "ENDED", order_end_date: @report.date_from..@report.date_to).each do |order| %>
      <tr>
        
        <td>
          Order number: <%= order.number %> | Sample name: <%= order.sample_name %>
        </td>

        <% col = order.measurements.count if col < order.measurements.count  %> 
          <% order.measurements.each do |meas| %>
            <td>
              <%= meas.technique.short_name %>: <%= meas.multiplier %>
            </td>
          <% end %> 
        
          <% if col < mcol  %>
          <% (mcol-col).times do %>
          <td></td>
          <% end %>
          <% end %>
        
        <td>
          Koszt: <%= order.final_price %> zł
        </td>


      </tr>
      <% end %>

      <tr>
        <td colspan="<%= col + 1 %>"><b>Koszt sumaryczny:</b></td>
        <td><%= client.orders.where(grant_id: grant.id).sum(:final_price) %> zł</td>
      </tr>


      </table>


    </td>

                        <% end %>




  <% end %>   
  </tr>








              <% end %>

  

  <% end %>

</table>


<%= link_to 'Edit', edit_report_path(@report), class: "btn btn-default"%> |
<%= link_to 'Back', reports_path, class: "btn btn-default" %>

app/views/reports/showpdf.html.erb
<%= wicked_pdf_stylesheet_link_tag 'application' %>

<table class="table table-condensed">
  <tr class="success">
    <td><h4>Raport: <%= @report.name %></h4></td>
    <td><h5><strong>Data wykonania od: </strong><%= @report.date_from %> <strong>do: </strong><%= @report.date_to %></h5></td>
  </tr>
</table>


      <% case @report.i_type
        when "NON-COMMERCIAL" %>
          <%= render 'niekomercyjne' %>
      <% when "1 INSTITUTION" %>
          <%= render 'icho' %>
      <% when "COMMERCIAL" %>
          <%= render 'niekomercyjne' %>
      <% when "1 GRANT" %>
          <%= render 'ichogrant' %>                           
        <% end %>
