config/routes.rb
require 'resque/scheduler/server'

Rails.application.routes.draw do

mount Resque::Server.new, :at => '/resque'

  resources :reports do
    member do
      get 'showpdf'
    end
  end

  resources :grants
  devise_for :users
  resources :measurements do
    get 'autocomplete_technique_name', :on => :collection
  end

  resources :techniques
  resources :measurements
  get 'static_pages/home'

  get 'static_pages/help'

  resources :teams
  resources :institutions do
    get 'get_institutions', :on => :collection
  end
  
  resources :clients do
    resources :orders
  end  

  match 'clients/get_team_options/:institution_id', :controller=>'clients', :action => 'get_team_options' , :via  => 'get'
  match 'clients/get_clients_in_team/:team_id', :controller=>'clients', :action => 'get_clients_in_team' , :via  => 'get'
  match 'clients/get_client_grants/:client_id', :controller=>'clients', :action => 'get_client_grants' , :via  => 'get'
  match 'orders/get_grant_options/:client_id', :controller=>'orders', :action => 'get_grant_options' , :via  => 'get'
  match 'teams/get_team_grants/:team_id', :controller=>'teams', :action => 'get_team_grants' , :via  => 'get'
  match 'institutions/get_clients/:institution_id', :controller=>'institutions', :action => 'get_clients' , :via  => 'get'

    get 'orders/gotindex/:status' => 'orders#gotindex'

  root 'static_pages#home'

  resources :orders do
    get 'autocomplete_client_name', :on => :collection
    post 'change_status', :on => :collection
    get 'get_alertcontent', :on => :collection
  end

  resources :orders

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	Orders Management in Mass Spectrometry Laboratory, app created by Paweł Świder
  </small>
  <nav>
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ORDERS", root_path, id: "logo" %>
        
        <nav>
          <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Hello  #{current_user.username}", '#' %></li>
          <% end %>
            <li><%= link_to "Home", root_path %></li>

           
    <li id="fat-menu" class="dropdown">
      <a href="/" class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#">New<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Institution", new_institution_path %></li>
              <li><%= link_to "Team", new_team_path %></li>
              <li><%= link_to "Client", new_client_path %></li>
              <li><%= link_to "Technique", new_technique_path %></li>              
              <li><%= link_to "Order", new_order_path %></li>                 
            </ul>
    </li>
    <li id="fat-menu" class="dropdown">
      <a href="/" class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#">List all<b class="caret"></b></a>
            <ul class="dropdown-menu">

              <li><%= link_to "Institutions", institutions_path %></li>
              <li><%= link_to "Teams", teams_path %></li>
              <li><%= link_to "Clients", clients_path %></li>
              <li><%= link_to "Orders", orders_path %></li>
              <li><%= link_to "Reports", reports_path %></li>
              <li role="separator" class="divider"></li>              
              <li><%= link_to "Techniques", techniques_path %></li>
              <li><%= link_to "Measurements", measurements_path %></li>             
              <li><%= link_to "Grants", grants_path %></li>             
              
            </ul>
    </li>

    <li id="fat-menu" class="dropdown">
      <a href="/" class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#">Account<b class="caret"></b></a>
            <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to "Edit account", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>              
            <% end %>

            </ul>
    </li>
    <li><%= link_to "Help", static_pages_help_path %></li>
        

          </ul>
        </nav>
      
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MS-DataBase</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container" style="width: 100%">    
  	      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>

  </body>

</html>